-- FrangLish · Módulo 4 · clases 16-20
-- Ejecutar DESPUÉS de classes_1_tables.sql

INSERT INTO course_classes (id, class_number, module_id, title, goal, grammar_focus, vocabulary, key_phrases, exercises, challenge, reading) VALUES

('c1000000-0000-0000-0000-000000000016', 16, 'f2000000-0000-0000-0000-000000000004',
 'Experiences at Work',
 'Hablar de anécdotas vividas en el trabajo y describir tus tareas y responsabilidades.',
 '["Reported speech en todos los tiempos: past simple, present perfect, past perfect, will, would, can", "Past Simple para narrar anécdotas", "Pronunciación de terminaciones verbales"]',
 '[{"term":"Anecdote","definition":"Anécdota, historia breve y real"},
   {"term":"To widen (eyes)","definition":"Abrir mucho los ojos por sorpresa"},
   {"term":"To hang up","definition":"Colgar el teléfono"},
   {"term":"To take time off","definition":"Tomarse días libres"},
   {"term":"Overtime","definition":"Horas extra"},
   {"term":"To take up (a course)","definition":"Apuntarse a un curso"}]',
 '["I remember when…",
   "Let me tell you about a time when…",
   "So the craziest thing happened at/yesterday/to…",
   "I believe you did… / For me, everything was… / Maybe try + gerund… next time."]',
 '[{"title":"Reported Speech (1)","instructions":"Convierte estas frases de estilo directo a estilo indirecto. Atención al tiempo verbal.","items":["Past simple: ''I fixed the bug by following the steps tech support sent me.''","Present Perfect: ''I haven''t designed for one year.''","Past Perfect: ''I had coded in Python before.''"]},
   {"title":"Reported Speech (2)","instructions":"Continúa con los modales y el futuro.","items":["Will: ''I''ll send you an email with the details of our next meeting.''","Would: ''I would like to improve my English skills, but I don''t have enough time to take up an English course.''","Can: ''I can code with JavaScript.''"]},
   {"title":"Practice: Past Tense pronunciation","instructions":"Elige un verbo y pide a un compañero que pronuncie su pasado; luego que cree una frase.","items":["assign, locate, edit, train, put, forget, approve, complete, check, organize, install, import","call, talk, contact, deliver, shock, instruct, pay, lift, open, share, think, come, consider","conduct, fire, believe, discuss, decide, reserve, produce, grab, manage, keep, look, send, go"]}]',
 '{"title":"Tell Us A Work Anecdote","scenario":"Menciona tu puesto actual o el último siguiendo la estructura, y luego cuenta una anécdota de trabajo. Quien escucha debe hacer una pregunta de seguimiento.","remember":["Estructura del puesto: Job Title · Company Name · Company Location · Years Worked · Company Description · Your Job Responsibilities","Usa past tense","Cuida la pronunciación de las terminaciones verbales","Usa reported speech","No aburras con una novela"]}',
 ''),

('c1000000-0000-0000-0000-000000000017', 17, 'f2000000-0000-0000-0000-000000000004',
 'Strengths & Weaknesses',
 'Práctica pre-entrevista: perfeccionar tu técnica de respuesta a las preguntas sobre fortalezas y debilidades.',
 '["Present Perfect para experiencia: I''ve always been… / haven''t had much experience with…", "Used to para hábitos pasados", "Second conditional: I could improve… if I ever needed to", "Evitar contracciones en registro formal"]',
 '[{"term":"To overcome (a weakness)","definition":"Superar una debilidad"},
   {"term":"Soft skills","definition":"Habilidades blandas: comunicación, liderazgo, empatía"},
   {"term":"Procrastination","definition":"Tendencia a dejar las cosas para después"},
   {"term":"Manageable chunks","definition":"Porciones manejables de un proyecto grande"},
   {"term":"To beat a deadline","definition":"Entregar antes de la fecha límite"},
   {"term":"Filler words","definition":"Muletillas: um, you know, like"}]',
 '["I am + certain / sure / excited to…",
   "I''ve always been on the… side of things and haven''t had much experience with…",
   "However, I''m a quick learner, and I believe I could improve… if I ever needed to.",
   "I decided that I needed to deal with the issue, so I…",
   "Now, I put together a plan as soon as I get a new assignment."]',
 '[{"title":"Select and Create","instructions":"Elige un verbo que conecte contigo y crea una frase que usarías en una entrevista.","items":["Assign, Coordinate, Execute, Review, Define, Detect, Evaluate, Extract, Investigate, Assemble","Build, Fix, Operate, Remodel, Repair, Allocate, Analyze, Conduct, Budget, Persuade","Ejemplo: I remodeled the entire office to enhance the team''s morale."]},
   {"title":"Evita estas palabras a toda costa","instructions":"Repasa qué NO decir en una entrevista.","items":["1. Muletillas sin sentido: ''um'', ''you know'', ''like''","2. Palabras descuidadas: ''kind of'', ''sort of'' — suenan poco profesionales","3. Palabras muy negativas: ''hate'' — transmite poca madurez emocional","4. Falta de confianza: ''perhaps'', ''maybe'', ''hopefully''","5. Slang: ''freaking'', ''my bad'', ''dude'' — no tienen lugar en una entrevista"]}]',
 '{"title":"Answer These Tough Interview Questions","scenario":"Uno es entrevistador y otro entrevistado. Responded a las preguntas difíciles.","remember":["What are some of your weaknesses?","How would you overcome your weakness?","What is your greatest strength?","Céntrate en tus soft skills","Usa ''I am + certain/sure/excited to…''","Evita las contracciones"],"example":"''Although I always met my deadlines, I used to have a problem with procrastination, and I''d end up working really long days as a deadline approached. I decided that I needed to deal with the issue, so I took classes on project management and time management. I learned how to organize my days and attack bigger projects in manageable chunks. Now, I put together a plan as soon as I get a new assignment, and I often beat my deadlines.''"}',
 ''),

('c1000000-0000-0000-0000-000000000018', 18, 'f2000000-0000-0000-0000-000000000004',
 'Career Ambitions',
 'Aprender a hablar de tus ambiciones profesionales: elige una empresa donde te gustaría trabajar y prepara tu discurso alineando tus metas con las de la empresa.',
 '["Future Perfect: By + time, subject + will have + past participle", "Future Perfect Continuous para duración", "Long-term vs short-term goals"]',
 '[{"term":"Ambition","definition":"Ambición, meta profesional"},
   {"term":"To align (goals)","definition":"Alinear tus metas con las de la empresa"},
   {"term":"Go-to company","definition":"La empresa de referencia en un sector"},
   {"term":"To spread awareness","definition":"Difundir concienciación sobre algo"},
   {"term":"Multilingual","definition":"Que habla varios idiomas"}]',
 '["By this time tomorrow, I will have…",
   "By next year, she will have…",
   "What are some of your long-term professional goals?",
   "What are some of your short-term professional goals?",
   "What do you hope for? / What do you wish for?",
   "What''s one goal that you want to accomplish next month?"]',
 '[{"title":"Future Perfect Activity (1-10)","instructions":"Completa el hueco con la forma correcta del verbo en Future Perfect.","items":["1. By this time tomorrow, I _____ (finish) the project. → will have finished","2. By 8 o''clock, the kids _____ (fall) asleep. → will have fallen","3. By tomorrow morning, he _____ (sleep) wonderfully. → will have slept","4. By next year, she _____ (receive) her promotion. → will have received","5. Robin _____ (sell) his car by next Sunday. → will have sold","6. I hope that I _____ (clean) the entire house by lunch. → will have cleaned","7. We _____ (dance) a few dances at the work party before midnight. → will have danced","8. At this time tomorrow morning, they _____ (begin) working. → will have begun","9. At this time next week, we _____ (catch) the thief. → will have caught","10. By 2013, I _____ (live) in Madrid for 5 years. → will have lived"]},
   {"title":"Future Perfect Activity (11-15)","instructions":"Continúa completando los huecos.","items":["11. In 2020, they _____ (work) here for 20 years. → will have worked","12. By September, Julie _____ (teach) us for over a year. → will have taught","13. By October, I _____ (study) English for 3 months. → will have studied","14. On Monday, she _____ (wait) for 2 weeks. → will have waited","15. Before Saturday, you _____ (do) all of your homework. → will have done"]},
   {"title":"Getting to Know You","instructions":"Pregunta a tus compañeros sobre sus metas.","items":["1. ¿Cuáles son tus metas profesionales a largo plazo?","2. ¿Y a corto plazo?","3. ¿Qué esperas conseguir?","4. ¿Qué deseas?","5. ¿Qué meta quieres cumplir el mes que viene?"]}]',
 '{"title":"Ambition Speech","scenario":"Piensa en la empresa de tus sueños. Imagina que tienes la oportunidad de trabajar para ellos. Comparte tus ambiciones profesionales asegurándote de que tus metas se alinean con las de la empresa.","remember":["Empresa 1: quiere empleados multilingües que puedan viajar y representar a la empresa","Empresa 2: quiere ser la empresa de referencia en Inteligencia Artificial","Empresa 3: quiere difundir que comer sano es posible con nuevas ideas de Food Tech","Empresa 4: quiere que todo empleado tenga acceso a educación tecnológica gratuita"]}',
 ''),

('c1000000-0000-0000-0000-000000000019', 19, 'f2000000-0000-0000-0000-000000000004',
 'Mock Interview',
 'Roleplay completo de una entrevista de trabajo: responder preguntas de RRHH y aprender a preguntar tú al final.',
 '["Quantifiers: many, much, a lot of, few, a little, some, any", "WH questions y Yes/No questions", "Future con will y going to en preguntas"]',
 '[{"term":"Asset","definition":"Activo — alguien valioso para la empresa"},
   {"term":"HR (Human Resources)","definition":"Recursos Humanos"},
   {"term":"Career development","definition":"Desarrollo profesional"},
   {"term":"Follow-up meeting","definition":"Reunión de seguimiento"},
   {"term":"Interviewee / Interviewer","definition":"Entrevistado / Entrevistador"}]',
 '["What are the career development opportunities in this company?",
   "Who do I schedule a follow-up meeting with?",
   "What challenges am I going to be facing?",
   "Why do you want to work for this company?",
   "What are your short and long term goals?"]',
 '[{"title":"Quantifier Activity 1","instructions":"Lee la frase y haz una pregunta relacionada que contenga un quantifier.","items":["We have many things to do this week. → How many things need to be done?","I don''t like any of those solutions.","Albert and Sandy have a lot of meetings next month.","We only have a few minutes until our next meeting.","Ana needs a little more information.","I would like to buy some English classes for the workers."]},
   {"title":"Quantifier Activity 2","instructions":"Crea tu propia pregunta ''Will there be…?'' usando un quantifier de la lista.","items":["Many · Much · A lot · A lot of · Few · A little more · A bit of · Some · Any"]},
   {"title":"Memory Connect","instructions":"Cierra los ojos; un compañero dice una palabra y tú cuentas el primer recuerdo que te viene.","items":["Ejemplo — Student A: ''Foam'' · Student B: ''I remember crying at a foam party because I got lost in the foam.''"]}]',
 '{"title":"Roleplay a Job Interview","scenario":"A) El entrevistado pregunta sobre la empresa y el puesto, e intenta convencer de que la empresa es la mejor para desarrollar su carrera, mostrando que es un gran activo. B) RRHH hace las preguntas clave.","remember":["Why do you want to work for this company?","What is your greatest strength? And weakness?","How would you overcome your weakness?","What are your short and long term goals?","Al final: haz 2 preguntas tú (WH o Yes/No). Espera a que respondan antes de la siguiente."]}',
 ''),

('c1000000-0000-0000-0000-000000000020', 20, 'f2000000-0000-0000-0000-000000000004',
 'Ask Confidently',
 'Aprender a no tener miedo de preguntar: practicar preguntas, repasar quantifiers y manejar idioms de proyecto.',
 '["Quantifiers en preguntas", "Future con Will y Going to", "WH questions y Yes/No questions", "Idioms de proyecto"]',
 '[{"term":"In the pipeline","definition":"Algo que se está preparando y ocurrirá pronto"},
   {"term":"Get the ball rolling","definition":"Poner algo en marcha, empezar"},
   {"term":"Too much / a lot on your plate","definition":"Estar muy ocupado, desbordado de tareas"},
   {"term":"At the eleventh hour","definition":"En el último momento posible"},
   {"term":"Make headway","definition":"Avanzar hacia algo difícil"},
   {"term":"To slack (a bit)","definition":"Aflojar el ritmo, descuidarse"}]',
 '["Tell the client their project is in the pipeline.",
   "We really need to get the ball rolling.",
   "Sherry has a lot on her plate, could you please help her conduct the interviews.",
   "The client agreed to extend the deadline at the eleventh hour.",
   "We had some problems with the user interface at first, but we are making headway now."]',
 '[{"title":"Discussion opener","instructions":"Debate en grupo.","items":["In general, what are some questions people are afraid of asking?"]},
   {"title":"Quantifier Activity 1","instructions":"Lee la frase y haz una pregunta con quantifier.","items":["We have many things to do this week. → How many things need to be done?","I don''t like any of those solutions.","Albert and Sandy have a lot of meetings next month.","We only have a few minutes until our next meeting.","Ana needs a little more information.","I would like to buy some English classes for the workers."]},
   {"title":"Quantifier Activity 2","instructions":"Crea tu pregunta ''Will there be…?'' con un quantifier.","items":["Many · Much · A lot · A lot of · Few · A little more · A bit of · Some · Any"]}]',
 '{"title":"Asking Questions at the End of an Interview","scenario":"Estás al final de una entrevista. Haz preguntas al entrevistador: WH questions y Yes/No questions, usando futuro con Will y Going to.","remember":["Espera a que el entrevistador responda antes de hacer otra pregunta","Ejemplo: What are the career development opportunities in this company?","Ejemplo: What challenges am I going to be facing?"]}',
 '')

ON CONFLICT (class_number) DO NOTHING;
