-- FrangLish · Módulo 1 · clases 1-5
-- Ejecutar DESPUÉS de classes_1_tables.sql

INSERT INTO course_classes (id, class_number, module_id, title, goal, grammar_focus, vocabulary, key_phrases, exercises, challenge, reading) VALUES

('c1000000-0000-0000-0000-000000000001', 1, 'f2000000-0000-0000-0000-000000000001',
 'Work Relationships',
 'Aprender a construir relaciones profesionales: hacer small talk, presentarte por completo y hablar de tus habilidades y perfil profesional.',
 '["Verb patterns: transitive, intransitive y linking (copular) verbs", "Present Simple para describir tu rol y tu empresa", "Present Perfect Continuous en preguntas: How long have you been working…?", "Irregular verbs para dar personalidad a tu perfil"]',
 '[{"term":"Mingle","definition":"Circular y conversar con varias personas en un evento o equipo"},
   {"term":"Transitive verb","definition":"Verbo que necesita objeto directo: Our company develops apps"},
   {"term":"Intransitive verb","definition":"Verbo sin objeto directo: The project manager quit"},
   {"term":"Linking (copular) verb","definition":"Verbo que conecta sujeto con descripción: The client looks stressed out"},
   {"term":"To put forward (an idea)","definition":"Proponer o presentar una idea"},
   {"term":"Ramble","definition":"Hablar sin parar y sin estructura — a evitar"}]',
 '["Hi, my name is ___. I work in ___. And you are?",
   "It''s nice to meet you! / It''s a pleasure to meet you!",
   "How long have you been working for the company?",
   "Do you work alone or as part of a team?",
   "Are you having a busy week?",
   "What are you working on?",
   "That''s great to hear… / How cool is that? / That''s good news!",
   "What happened next?"]',
 '[{"title":"Small talk en pareja","instructions":"Practica el diálogo de apertura y responde con las cuatro reacciones cortas.","items":["A: Hi, my name is ___. I work in ___. And you are?","B: Hello, I''m ___. I work in ___","A: It''s nice to meet you, ___!","B: It''s a pleasure to meet you!"]},
   {"title":"Perfil profesional (5 min escritos)","instructions":"Escribe tu perfil profesional en 5 minutos. Tip experto: usa verbos irregulares para que sea único.","items":["¿Cuáles son tus habilidades profesionales?","¿Cuáles son esas 5 características que todos tenemos?","¿Qué te da tu conocimiento?","¿Qué no se puede medir en una entrevista?","¿Cómo identificas tus habilidades profesionales?"]},
   {"title":"Guess the Verb Pattern","instructions":"Identifica si el verbo es transitive, intransitive o linking (copular).","items":["1. The client looks stressed out. → linking","2. Our company develops apps for multinational platforms. → transitive","3. Carl''s project manager quit. → intransitive","4. Tom listens to his team as they put forward ideas. → intransitive + transitive","5. Give James the new schedule once the meeting ends. → transitive (ditransitive)","6. The project runs at noon. → intransitive"]}]',
 '{"title":"Introduce Yourself!","scenario":"Preséntate completamente ante el grupo, como lo harías ante un equipo nuevo o un cliente.","remember":["Incluye tu nombre completo","Incluye la empresa, tus habilidades y tu puesto","Menciona un dato de un proyecto actual","Cuida el tiempo verbal","No divagues — corto y directo"],"example":"My name is Nancy Smith, and I''m the marketing director at Wise Technology. We''re developing some innovative marketing campaigns designed to engage new customers right in the streets of Manhattan. I''ve been recruiting local businesses that want to get involved in these activities. I love chatting with residents around the area and learning more about what they''re looking for from their smart devices."}',
 ''),

('c1000000-0000-0000-0000-000000000002', 2, 'f2000000-0000-0000-0000-000000000001',
 'Team Meeting',
 'Hacer roleplay de una reunión de actualización: contar lo que has hecho hasta ahora, definir el siguiente paso y asignar tareas al equipo.',
 '["Present Perfect para lo hecho hasta ahora: what you have done so far", "Past Simple regular e irregular", "Future con Will / Going to para los próximos pasos", "Pronunciación de terminaciones -ed: /d/, /id/, /it/"]',
 '[{"term":"So far","definition":"Hasta ahora — marcador típico de Present Perfect"},
   {"term":"Take effect","definition":"Surtir efecto, entrar en vigor"},
   {"term":"Glitch","definition":"Fallo técnico pequeño e inesperado"},
   {"term":"Put the project forward","definition":"Hacer avanzar el proyecto"},
   {"term":"Assign tasks","definition":"Repartir tareas entre el equipo"},
   {"term":"Follow-up question","definition":"Pregunta de seguimiento tras una intervención"}]',
 '["First, I/we + past verb + phrase",
   "Second, I/we + past verb / phrasal verb + phrase",
   "Then, I/we + past verb + phrase",
   "After that, I/we + past verb + phrase",
   "Finally, I/we + past verb + phrase"]',
 '[{"title":"Classify the verbs","instructions":"¿Qué grupo de verbos es regular y cuál irregular?","items":["Grupo A: be, send, come, have, set, bring, think, break, buy, lose → IRREGULAR","Grupo B: work, pass, inform, talk, call, finish, arrive, start, plan, code → REGULAR"]},
   {"title":"Pronunciación del pasado simple","instructions":"Clasifica cada verbo según su terminación: /d/, /id/ o /it/.","items":["/id/ → needed, wanted, waited, added, accepted, assisted, estimated, interrupted","/d/ → remembered, travelled, cleaned, complained, achieved, agreed, allowed, called, changed, earned, listened","/t/ → asked, typed, talked, thanked, purchased, helped, hoped, copied"]},
   {"title":"Go-To Speech Structure","instructions":"Construye tu update usando la estructura de 5 pasos.","items":["First, we implemented the new code the client gave us.","Second, we waited for it to take effect.","Then, we noticed that there were some glitches that needed to be fixed.","After that, we updated the client with our progress.","Finally, we were able to put the project forward."]}]',
 '{"title":"Roleplay: Update Meeting","scenario":"Simula una reunión de actualización con tu equipo. Cuenta lo hecho, define los siguientes pasos y asigna tareas.","remember":["Haz small talk","Sé cortés","Menciona lo que has hecho hasta ahora (Present Perfect)","Habla de los próximos pasos con will / going to","Cuida las terminaciones del pasado","Escucha activamente","Haz preguntas de seguimiento"]}',
 ''),

('c1000000-0000-0000-0000-000000000003', 3, 'f2000000-0000-0000-0000-000000000001',
 'Effective Emailing',
 'Entender y responder emails profesionales usando vocabulario y estructuras que hagan tu respuesta clara y formal.',
 '["Modales para peticiones y respuestas formales", "Gerundios tras preposición: Thanks for + noun/-ing, I would appreciate your help in + -ing", "Estructura de email formal: apertura, cuerpo, cierre"]',
 '[{"term":"Deal with","definition":"Resolver o gestionar un problema, o realizar una tarea"},
   {"term":"Repurpose","definition":"Cambiar algo para que sirva a otro propósito"},
   {"term":"Waste","definition":"Material desechado tras completar un proceso"},
   {"term":"(It has) come to our attention","definition":"Hemos notado / nos hemos dado cuenta de"},
   {"term":"Deem fit","definition":"Considerar apropiado o efectivo"},
   {"term":"Discard","definition":"Desechar, tirar a la basura"},
   {"term":"Landfill","definition":"Vertedero donde se entierra la basura"},
   {"term":"A proposition","definition":"Propuesta o plan de acción, especialmente en contexto de negocios"}]',
 '["Thanks for + noun or -ING…",
   "Please feel welcomed to…",
   "I hope all is well.",
   "I would appreciate your help in + -ING…",
   "Looking forward to hearing from you.",
   "My apologies for…",
   "I understand ''x'' has caused ''y''… to/but…",
   "I wanted to update you on…",
   "I''d be happy to…",
   "I see no problem with… + gerund…",
   "How about…?"]',
 '[{"title":"Practice: Responding to Emails","instructions":"Usa las frases clave para responder a estas peticiones y requerimientos.","items":["1. I would like to set up a meeting with your sales team. Will that be a possibility?","2. We noticed that two team members are making many mistakes. We would like them replaced.","3. The website has crashed once again. I thought you promised it would never happen again.","4. Could you tell me when the product is expected to launch?","5. The marketing campaign that was presented to us is not what we are looking for."]},
   {"title":"Comprensión lectora: el email de Kelly Wells","instructions":"Lee el email de la bandeja de entrada y elige la respuesta correcta.","items":["1. ¿Con qué tipo de empresas trabaja Kelly? → c. Technology","2. Los microchips viejos actualmente están siendo… → c. discarded to landfill","3. ¿Qué quiere hacer Science Solutions con los residuos? → a. Purchase it","4. ¿Qué se beneficiará de esto? → c. Both","5. ¿Cómo quiere Kelly seguir la conversación? → c. In a meeting"]}]',
 '{"title":"Reading and Responding to Emails","scenario":"Recibirás un email que leerás en silencio y responderás. Después leerás en voz alta tu email y tu respuesta ante la clase.","remember":["Asegúrate de responder TODO lo que se pregunta, de forma formal","Usa modales","Haz preguntas si es necesario","Usa vocabulario y frases de módulos anteriores"]}',
 'EMAIL IN INBOX — To: Richard McGrath · Subject: Recycling Opportunity

Dear Mr. McGrath,

I work in the recycling department at Science Solutions. I deal with repurposing waste from technology companies.

It has come to our attention that the microchips you no longer deem fit for purpose are being discarded to landfill.

I wonder if you are aware that we could purchase this waste from you? Such a proposition would benefit both your company and the environment.

I would welcome the opportunity to discuss this further with you in a meeting.

Best regards,
Kelly Wells'),

('c1000000-0000-0000-0000-000000000004', 4, 'f2000000-0000-0000-0000-000000000001',
 'Team Communication',
 'Aprender a comunicarte con el equipo: describir una tarea grande, hacer peticiones corticales y anunciar una reunión de planificación con su agenda usando WILL.',
 '["Complex past tenses para describir lo ya ocurrido", "Future con WILL para la agenda de la reunión", "Peticiones corteses con Could you…? / Do you mind…? / Would you…?", "Registro formal vs. informal"]',
 '[{"term":"Clock in / clock out","definition":"Fichar al entrar / al salir del trabajo"},
   {"term":"Peer-to-peer critique","definition":"Revisión entre compañeros del mismo nivel"},
   {"term":"Stakeholder","definition":"Parte interesada en el proyecto"},
   {"term":"Backup (person)","definition":"Persona que cubre a otra cuando falta"},
   {"term":"On the dot","definition":"Puntualmente, a la hora exacta"},
   {"term":"Call in sick","definition":"Avisar de que no vas a trabajar por enfermedad"},
   {"term":"Rain check","definition":"Dejarlo para otra ocasión"},
   {"term":"Up to standards","definition":"A la altura de lo esperado"}]',
 '["Could you…?", "Do you mind…?", "Would you…?",
   "May I ask why?",
   "I completely understand. Keep in mind that…",
   "If you look here / at…",
   "Thanks, I appreciate it."]',
 '[{"title":"Describe a task","instructions":"Describe una tarea grande a tu equipo. Imagina que usas gráficos, documentos y diapositivas.","items":["Sé detallado pero conciso","Usa ''If you look here/at…''","Haz al menos dos peticiones corteses","No divagues"]},
   {"title":"That Doesn''t Sound Nice","instructions":"Empareja la frase cortés con su equivalente brusco.","items":["a. Could you give me a second, please? ↔ 2. Not now!","b. Can we talk a bit later? ↔ 8. Rain check.","c. I''m onboard. ↔ 1. Yes.","d. I have another option. ↔ 6. I don''t like that idea","e. I think you might be mistaken ↔ 10. You''re wrong","f. I have a few concerns ↔ 5. That''s a bad idea","g. I would prefer to do it another way ↔ 7. No.","h. Could you explain this to me? ↔ 3. What is this?","i. Would you mind telling me what you don''t understand? ↔ 9. Not again","j. This report is not up to standards. ↔ 4. This is awful, incomplete."]},
   {"title":"Scenario roleplay","instructions":"Resuelve el escenario asignado a tu equipo usando peticiones corteses.","items":["Team 1: Issues with the meeting schedule","Team 2: Some miscommunication with the client"]}]',
 '{"title":"Time to Make Polite Requests","scenario":"Un compañero llamó diciendo que está enfermo. Negocia con otro miembro del equipo que cubra su turno.","remember":["Usa frases de apertura corteses","Explica el porqué si te lo piden","Reconoce y agradece"],"example":"Team Leader: ''James, could you stay an extra hour?'' / James: ''May I ask why?'' / Team Leader: ''Taylor called in sick and you are his backup.'' / James: ''I completely understand. Keep in mind that I have to leave on the dot.'' / Team Leader: ''Thanks, I appreciate it.''"}',
 ''),

('c1000000-0000-0000-0000-000000000005', 5, 'f2000000-0000-0000-0000-000000000001',
 'Self Appraisal',
 'Intercambiar feedback sobre tu progreso y aprender técnicas para mejorar tus habilidades de speaking. Cierre del Módulo 1.',
 '["Present Perfect para logros: I have improved / I have gotten a better command of…", "Still + need to para lo pendiente", "First conditional: If I…, I will…", "Frases de opinión"]',
 '[{"term":"Self appraisal","definition":"Autoevaluación de tu propio desempeño"},
   {"term":"To get a better command of","definition":"Adquirir mayor dominio de algo"},
   {"term":"To incorporate","definition":"Integrar algo nuevo a tu forma de trabajar"},
   {"term":"Fish out of water","definition":"Sentirse fuera de lugar o incómodo en una situación"},
   {"term":"To get along","definition":"Llevarse bien con alguien"}]',
 '["I have improved / enhanced…",
   "I have gotten a better command of…",
   "I have incorporated…",
   "I''ve corrected…",
   "However, I still need to…, and also…",
   "I''m confident that if I…, I will accomplish…",
   "I think… / I believe… / I feel… / I suppose… / I guess…",
   "In my opinion… / In my view… / In my eyes… / It seems to me that…",
   "From my perspective… / From my point of view… / From my viewpoint…"]',
 '[{"title":"Checklist del Módulo 1","instructions":"Marca lo que has mejorado y responde: ¿qué has hecho para mejorar? ¿qué te falta?","items":["1. Present, past and future simple tenses","2. Formal Emailing","3. Most common phrasal verbs","4. Pronunciación de ''-ed''","5. Polite English"]},
   {"title":"Listening: True or False","instructions":"Escucha y decide si cada afirmación es verdadera o falsa.","items":["El cliente es un sitio web internacional popular con más de 10 años en el mercado","Emilia está demasiado cansada para asistir a la reunión, así que Stephanie prepara café","Stephanie y Emilia parecen llevarse muy bien","En la reunión el equipo de desarrollo está junto al equipo de ventas","Stephanie se sintió como pez fuera del agua porque no pudo decir ni una palabra en inglés"]}]',
 '{"title":"Self Review","scenario":"Haz tu autoevaluación del Módulo 1 usando la estructura de frases, y comparte tu opinión sobre cómo fijar metas para mejorar tu inglés.","remember":["Usa Present Perfect para lo logrado","Reconoce lo que aún falta con ''I still need to…''","Cierra con un first conditional de compromiso"]}',
 '')

ON CONFLICT (class_number) DO NOTHING;
