-- FrangLish · Módulo 5 · clases 21-24
-- Ejecutar DESPUÉS de classes_1_tables.sql

INSERT INTO course_classes (id, class_number, module_id, title, goal, grammar_focus, vocabulary, key_phrases, exercises, challenge, reading) VALUES

('c1000000-0000-0000-0000-000000000021', 21, 'f2000000-0000-0000-0000-000000000005',
 'Communicating with IT',
 'Aprender a hablar con soporte técnico: reportar un incidente de seguridad, escuchar activamente y entender la explicación técnica.',
 '["Modal perfects para especular: what could have actually happened", "Past Simple para reportar incidentes", "Second conditional: How would you feel if…?"]',
 '[{"term":"ID theft","definition":"Robo de identidad"},
   {"term":"Breach","definition":"Brecha de seguridad, violación del sistema"},
   {"term":"To get locked out","definition":"Quedarse fuera del sistema por olvidar la contraseña"},
   {"term":"To crash (a system)","definition":"Colapsar, caerse un sistema"},
   {"term":"Disruption","definition":"Interrupción del servicio"},
   {"term":"Spam email","definition":"Correo no deseado"},
   {"term":"To look into (a problem)","definition":"Investigar un problema"},
   {"term":"To implement (steps)","definition":"Aplicar los pasos indicados"}]',
 '["I tried to access a document but it didn''t open.",
   "I implemented the steps that you gave me but it didn''t work.",
   "I looked into the problem and provided you with the necessary steps to correct it.",
   "I couldn''t remember my password and I got locked out.",
   "My system crashed for the fifth time today."]',
 '[{"title":"Oh No! I Have a Tech Issue","instructions":"Responde a uno de estos mensajes como si fueras Soporte Técnico.","items":["1. I tried to access a document but it didn''t open.","2. I implemented the steps that you gave me but it didn''t work.","3. I looked into the problem and provided you with the necessary steps to correct it.","4. I couldn''t remember my password and I got locked out.","5. My system crashed for the fifth time today."]},
   {"title":"Let''s Discuss","instructions":"Debate estas preguntas usando el second conditional cuando encaje.","items":["1. ¿Alguien ha sufrido un robo de identidad?","2. ¿Has abierto alguna vez un correo spam?","3. ¿Cómo te sentirías si te robaran la identidad?","4. ¿Qué sería lo primero que harías para recuperar tu identidad?","5. ¿Qué pasos darías para evitar que te roben la identidad?"]}]',
 '{"title":"Alert: There''s Been A Breach","scenario":"A un miembro del equipo le robaron su tarjeta de identificación y se usó para acceder a la sala de servidores. El hacker causó una interrupción en la red. Otro miembro lo detectó y avisó a IT. El equipo y el técnico de IT están reunidos discutiendo cómo arreglar la brecha y evitar que se repita.","remember":["Usa el vocabulario técnico de la clase","Escucha activamente la explicación de IT","Especula con modal perfects: it could have been…"]}',
 ''),

('c1000000-0000-0000-0000-000000000022', 22, 'f2000000-0000-0000-0000-000000000005',
 'Problem Solving Meeting',
 'Usar vocabulario y frases nuevas para participar en una discusión de grupo sobre un plan de acción ante un problema del proyecto.',
 '["Frases de opinión avanzadas (sin usar ''in my opinion'' ni ''I think'')", "Interrumpir educadamente", "Reformular frases débiles en propuestas firmes"]',
 '[{"term":"Action plan","definition":"Plan de acción"},
   {"term":"To reboot (a server)","definition":"Reiniciar un servidor"},
   {"term":"To touch base","definition":"Ponerse en contacto brevemente — frase a evitar por vaga"},
   {"term":"To interrupt","definition":"Interrumpir — a veces necesario en una reunión"},
   {"term":"Meeting agenda","definition":"Orden del día de la reunión"}]',
 '["From my perspective… / From my point of view…",
   "It seems to me that… / As I see it…",
   "The way I see it… / Based on the data…",
   "I''d like to add… / If I may interject…"]',
 '[{"title":"Let''s Talk: Action Plan Meetings","instructions":"Debate en grupo estas tres preguntas.","items":["¿Qué tareas podría pedirte un líder de equipo para resolver un problema?","¿Cuáles son algunos de los roles en una reunión de plan de acción?","¿Qué cosas no deberías decir nunca en una reunión de plan de acción?"]},
   {"title":"Practice: Replace the Phrase","instructions":"Estas frases deben evitarse. Ofrece una alternativa mucho mejor.","items":["1. ''Maybe we should try rebooting the server.'' → ''Based on the logs, rebooting the server will resolve this.''","2. ''I think this would work for us.'' → ''From my perspective, this is the strongest option because…''","3. ''I just wanted to touch base with you on the meeting agenda.'' → ''I''d like to confirm the meeting agenda.''","4. ''Sorry.'' → ''Thank you for your patience.''","5. ''I hate to ask but I was wondering if we could move the call to 2 p.m. on Friday?'' → ''Could we move the call to 2 p.m. on Friday?''"]}]',
 '{"title":"Action Plan Discussion","scenario":"Ha habido un problema con el proyecto y el equipo necesita reunirse para discutir un plan de acción.","remember":["Cuida el tiempo verbal","Usa frases de opinión — pero NO ''in my opinion'' ni ''I think''","No tengas miedo de interrumpir cuando sea necesario"]}',
 ''),

('c1000000-0000-0000-0000-000000000023', 23, 'f2000000-0000-0000-0000-000000000005',
 'Room for Improvement',
 'Aprender a ofrecer y recibir feedback constructivo en el trabajo.',
 '["First conditional para feedback: If I get feedback, I''ll be able to improve…", "Modales para suavizar la crítica: could, might, would", "Estructura de peer feedback escrito"]',
 '[{"term":"Constructive feedback","definition":"Feedback constructivo, orientado a mejorar"},
   {"term":"Room for improvement","definition":"Margen de mejora"},
   {"term":"To keep up with","definition":"Mantener el ritmo de"},
   {"term":"Team player","definition":"Persona que trabaja bien en equipo"},
   {"term":"Work-life balance","definition":"Equilibrio entre vida laboral y personal"},
   {"term":"Performance report","definition":"Informe de desempeño"},
   {"term":"To go over (a situation)","definition":"Abordar o repasar una situación"}]',
 '["If I get feedback, I''ll be able to improve at work…",
   "If I don''t get feedback, I will not know how to do a better job…",
   "If my boss tells me that I have to improve my productivity, I''ll ask for tools to meet that goal.",
   "I feel that you could achieve more by…",
   "You did a great job of/with…",
   "However, I do have a few suggestions for improvement. One,… Two,…"]',
 '[{"title":"First Conditional Phrases","instructions":"Estudia los ejemplos y añade tus propias frases en first conditional sobre el feedback.","items":["''If I get feedback, I''ll be able to improve at work…''","''If I don''t get feedback, I will not know how to do a better job…''","''If my boss tells me that I have to improve my productivity, I''ll ask for tools to meet that goal''"]},
   {"title":"Use modals and share feedback","instructions":"Da feedback constructivo para cada escenario usando modales.","items":["Escenario 1: Empleado trabajador pero llega tarde con frecuencia. → ''Hi Carla, I was going through everyone''s performance report from the last few months, and I must say you have done a great job. Also, I feel that you could achieve more every day by coming early, and that way, you''ll also be able to maintain a sound work-life balance.''","Escenario 2: Pablo rinde muy bien solo pero evita trabajar en equipo.","Escenario 3: Ruby es de las mejores del equipo en rendimiento pero le cuesta comunicarse."]},
   {"title":"Peer Feedback escrito","instructions":"Elige un compañero y completa la estructura con información sobre sus habilidades de speaking.","items":["Dear [Name of peer],","I had the chance to review your work and wanted to share some feedback with you. Firstly, I thought your… .","You did a great job of/with… .","However, I do have a few suggestions for improvement. One, … Two,…","Overall, I think you did … with your project.","I hope you find my feedback helpful, and I''m happy to discuss any of these points further.","Best, [Your name]"]}]',
 '{"title":"Time to Debate","scenario":"Tu líder de proyecto te ha pedido hacer horas extra para complacer al cliente y entregar la tarea antes de lo previsto. Sabes que este cliente es muy importante para la empresa, pero quieres defender tu postura. Propón alternativas.","remember":["Mira el vídeo ''How to use English to help you participate in Tech meetings''","Toma nota de las frases y vocabulario del vídeo","Propón distintas alternativas para resolver la situación"]}',
 ''),

('c1000000-0000-0000-0000-000000000024', 24, 'f2000000-0000-0000-0000-000000000005',
 'Review Meeting',
 'MÓDULO 5 · Consolidación: usar frases, modales y el first conditional para dar feedback de desempeño sobre cómo mejorar.',
 '["Modales para feedback: could, should, might want to, would love to see", "First conditional para consecuencias positivas", "Estructura positivo + área de mejora"]',
 '[{"term":"To raise your voice","definition":"Levantar la voz"},
   {"term":"One-on-one meeting","definition":"Reunión individual entre jefe y empleado"},
   {"term":"Quarterly results","definition":"Resultados trimestrales"},
   {"term":"Prioritization","definition":"Priorización de tareas"},
   {"term":"To be left out of the loop","definition":"Quedarse fuera de la información"},
   {"term":"To go off track","definition":"Desviarse del tema"},
   {"term":"Unmet deadlines","definition":"Plazos incumplidos"},
   {"term":"To manage expectations","definition":"Gestionar las expectativas del cliente"},
   {"term":"To outdo yourself","definition":"Superarte a ti mismo"}]',
 '["If you plan your daily tasks you''ll be more productive.",
   "You might want to try an app to help you.",
   "I would love to see you do more [action] because [reason].",
   "I encourage you to start [action] because it will help you [intended result].",
   "It would be nice if you…",
   "Even though you…, going forward I would like it if you…",
   "You outdid yourself last month when…",
   "Your ______ has improved. / Great job with…",
   "When it comes to + topic… you are…"]',
 '[{"title":"Modal Practice: Improvement Phrases","instructions":"Empareja cada frase de mejora con la consecuencia que mejor encaja (A-H).","items":["1. When you raise your voice during discussions, you make other people uncomfortable. → D. This is something you should be aware of and not do moving forward.","2. I''m aware that you cancel your one-on-one meetings almost every week. → F. This shouldn''t happen again, given you''re a manager responsible for the career growth of multiple employees.","3. I would like to see you stop waiting until the last minute to prepare your quarterly results. → A. Your presentations tend to be scattered and don''t represent your team''s efforts well.","4. I think you could improve the way you share updates with the rest of the team. → E. Sometimes, people get left out of the loop so not everyone is on the same page.","5. An area you could improve on is prioritization — you''re always so willing to jump into new projects. → H. Which is great, but that results in unmet deadlines.","6. I think you could improve on staying focused during meetings and brainstorms. → G. Discussions frequently go off track because you want to take them in another direction.","7. An area of improvement to consider is the way you edit other people''s work. → B. It would be helpful to explain why you update something instead of changing it without context.","8. You could improve the way you manage expectations with our customers. → C. They don''t end up disappointed or upset down the road."]},
   {"title":"Can You Present a Perfect Statement?","instructions":"Completa: la primera parte es positiva, la segunda debe ser una mejora.","items":["Ejemplo: You helped the team acquire 5 new accounts and by doing so, we are #1 in the market but you haven''t acquired an account on your own so you need to connect with clients on a one-on-one basis this month.","1. You attended five events and exceeded your sales quota by 10% this quarter but you haven''t_____ so you need to_____.","2. You set up multiple goal checkpoints, which led to the marketing team hitting all its Q1 KPIs but you haven''t_____ so you need to_____.","3. You implemented a new update, which resulted in a 10% increase in website engagement but you haven''t_____ so you need to_____.","4. You finished a content audit and pinpointed the gaps we need to address in Q2 but you haven''t_____ so you need to_____.","5. You planned a successful PR offsite and the team produced three fresh story angles but you haven''t_____ so you need to_____."]},
   {"title":"Thanks for the Compliment","instructions":"Usa una frase de arranque para elogiar las habilidades de speaking de un compañero.","items":["''You outdid yourself last month when…''","''Your ______ has improved.''","''Great job with…''","''When it comes to + topic… you are…''","''You always make sure to…''","''Your speaking skills could use … but overall …''","''I know that + topic + isn''t/aren''t + but + present perfect…''","Ejemplo: I know phrasal verbs aren''t your favorite but I''ve never seen you use them better than today. Great job."]}]',
 '{"title":"Performance Review Meeting","scenario":"Uno de vosotros es el PM y tiene una reunión con su equipo. Necesitas dar feedback sobre cómo mejorar. Después, el equipo aconseja al PM sobre cómo puede mejorar él.","remember":["TM 1: tímido, no habla, nunca participa, pasa desapercibido","TM 2: olvida darle a ''enviar'', siempre llega tarde, parece dormido","TM 3: usa Slack para discutir, habla mal al cliente, parece antipático en las videollamadas","TM 4: nunca está preparado, llega tarde a las reuniones, usó la misma excusa 4 veces","Da siempre la bienvenida al equipo primero","Di de qué trata la reunión","Sé constructivo con tus frases de mejora"]}',
 '')

ON CONFLICT (class_number) DO NOTHING;
