-- FrangLish · Módulo 2 · clases 6-10
-- Ejecutar DESPUÉS de classes_1_tables.sql

INSERT INTO course_classes (id, class_number, module_id, title, goal, grammar_focus, vocabulary, key_phrases, exercises, challenge, reading) VALUES

('c1000000-0000-0000-0000-000000000006', 6, 'f2000000-0000-0000-0000-000000000002',
 'Successful Projects',
 'Contar cómo entregaste con éxito una solución en un proyecto que liderabas o en el que participabas.',
 '["Past Simple y Past Continuous para narrar: Last year, while I was working for…", "Reported/recommendation structures: I recommended that the CEO implement…", "Phrasal verbs de resolución de problemas"]',
 '[{"term":"Deal with (a problem)","definition":"Gestionar, manejar un problema"},
   {"term":"Run into (a problem)","definition":"Encontrarse un problema de forma inesperada"},
   {"term":"Sort out","definition":"Resolver con éxito un problema"},
   {"term":"Tackle (a problem)","definition":"Intentar afrontar un problema"},
   {"term":"Understaffed","definition":"Con falta de personal"},
   {"term":"Engagement","definition":"Nivel de interacción del público con tu contenido"},
   {"term":"To gather information","definition":"Recopilar información"}]',
 '["What? = el problema concreto",
   "When? = cuándo y dónde ocurrió",
   "Solution? = qué hiciste y qué resultado tuvo",
   "I checked if…",
   "I decided to…",
   "After gathering the information, I was able to see…",
   "I recommended that…",
   "…increased by 85% and we successfully sorted out the problem."]',
 '[{"title":"We got a problem!","instructions":"Elige un problema y explica cómo lo resolverías siguiendo la estructura What / When / Solution.","items":["Problem 1: A client got upset due to a misunderstanding about pricing.","Problem 2: Four team members quit the same week and now the department is understaffed.","Problem 3: The company''s social media engagement has substantially decreased."]},
   {"title":"Modelo de estructura","instructions":"Estudia el ejemplo y replica la estructura con tu propio caso.","items":["What? = Our team productivity decreased","When? = Last year, while I was working for (xx company)","Solution? = I decided to send the team a survey. After gathering the information, I was able to see where the problem was coming from. I recommended that the CEO implement a new project management system. Productivity increased by 85% and we successfully sorted out the problem."]}]',
 '{"title":"Cuenta tu proyecto exitoso","scenario":"Comparte un proyecto real en el que resolviste un problema. Sigue la estructura de tres partes.","remember":["WHAT — cuál fue el problema","WHEN — cuándo y en qué contexto","SOLUTION — qué hiciste y qué resultado obtuviste (usa números)"]}',
 ''),

('c1000000-0000-0000-0000-000000000007', 7, 'f2000000-0000-0000-0000-000000000002',
 'Work Achievements',
 'Aprender a impresionar a un reclutador: preparar un discurso efectivo sobre un proyecto reciente y responder a "What are some of your biggest accomplishments?".',
 '["Sequence connectors: first, second, third, after, finally", "Correlative conjunctions: Not only… but also…", "Mezcla de verbos regulares e irregulares en pasado", "Phrasal verbs profesionales"]',
 '[{"term":"Accomplishment","definition":"Logro destacado"},
   {"term":"To handle","definition":"Gestionar, encargarse de"},
   {"term":"To inspect","definition":"Revisar en detalle"},
   {"term":"To arise / arose","definition":"Surgir (un problema, una oportunidad)"},
   {"term":"To go global","definition":"Expandirse internacionalmente"},
   {"term":"Emphasis","definition":"Énfasis — clave al presentar tus logros"}]',
 '["First, … Then, … Afterwards, … Now, …",
   "Not only did I…, but I also…",
   "I am proud to say that…",
   "What are some of your biggest accomplishments?"]',
 '[{"title":"Two Ways to Answer","instructions":"Responde la pregunta de entrevista de las dos formas.","items":["1) Sequence connectors + past tense: First, I earned my college degree in Finance. Then, I got my first job at Apple Inc. Afterwards, I started my own company. Now, I am proud to say that my business has gone global.","2) Correlative conjunctions: Not only did I earn my college degree at a young age but I also started my own company by the time I was 30."]},
   {"title":"Verb Buildup Time","instructions":"En equipo, generen todos los verbos que puedan relacionados con proyectos.","items":["Ejemplos: handled, created, inspected, took, arose, delivered, launched, coordinated, streamlined, negotiated"]}]',
 '{"title":"Time to Get Your Speech On","scenario":"Da un discurso verbal sobre el último proyecto en el que trabajaste o que completaste.","remember":["Usa sequence connectors (first, second, third, after, finally)","Usa vocabulario nuevo","Mezcla verbos regulares e irregulares","Incluye phrasal verbs","Pro tip: el énfasis es clave"]}',
 ''),

('c1000000-0000-0000-0000-000000000008', 8, 'f2000000-0000-0000-0000-000000000002',
 'Product Presentation',
 'Aprender a dar una presentación (Parte 1): presentar un producto de forma informativa cubriendo características, precio, público objetivo y marketing.',
 '["Present Perfect con since y for", "Estructura de presentación en 4 bloques", "Due to / compared to para causa y comparación"]',
 '[{"term":"Clicks","definition":"Número total de clics en tu anuncio"},
   {"term":"CTR (Click-Through Rate)","definition":"Clics recibidos dividido entre las veces que se mostró el anuncio"},
   {"term":"CPM (Cost per 1,000 Impressions)","definition":"Coste medio pagado por 1.000 impresiones del anuncio"},
   {"term":"An impression","definition":"Cada vez que el anuncio se muestra en pantalla"},
   {"term":"CPC (Cost per Click)","definition":"Importe gastado dividido entre los clics recibidos"},
   {"term":"Frequency","definition":"Número medio de veces que cada persona ve tu anuncio"},
   {"term":"Ad fatigue","definition":"Desgaste que sufre el público al ver el mismo anuncio repetidamente"},
   {"term":"Reach","definition":"Número de personas únicas que vieron tu anuncio"}]',
 '["The presentation today is about…",
   "The purpose of this presentation is…",
   "Why should customers choose your product?",
   "Are there any questions from the audience?",
   "Thank you for listening to my presentation.",
   "I have been trying to… for the past…",
   "I have + past participle + since 1987"]',
 '[{"title":"Advertising vocabulary in context","instructions":"Crea una frase que usarías en una presentación informativa de producto, usando al menos una palabra del vocabulario publicitario.","items":["Ejemplo: Due to ad fatigue our product reach was low compared to last month.","Ejemplo: The bright neon color will surely bring in those consumer clicks.","Ejemplo: We hope that the marketing video will improve our CPC."]},
   {"title":"GAME: Try Not To Laugh","instructions":"Usa Present Perfect con ''since'' y ''for'' para contar algo gracioso al grupo. Gana quien menos se ría.","items":["I have been trying to correctly pronounce ''entrepreneurship'' for the past twenty minutes.","I have ridden a pony to work since 1987.","Did you hear about the panda with no ears? No?… They didn''t either."]}]',
 '{"title":"Informative Presentation about a Product","scenario":"Da una presentación verbal informativa sobre un producto. Tienes 5 minutos para prepararla.","remember":["1. Introducción: saluda, presenta a tu grupo y el nombre de la empresa","2. Estado del propósito: ''The purpose of this presentation is…''","3. Info del producto: nombre, público objetivo y puntos de venta (puedes comparar con la competencia)","4. Conclusión con llamada a la acción: por qué elegir tu producto, qué acción tomar, pregunta si hay dudas y agradece"]}',
 ''),

('c1000000-0000-0000-0000-000000000009', 9, 'f2000000-0000-0000-0000-000000000002',
 'Report Presentation',
 'Aprender a dar una presentación (Parte 2): piensa en una fintech conocida (ej. PayPal) y presenta un informe de crecimiento interpretando gráficas.',
 '["Estructura SUBJECT + VERB + ADVERB para describir cambios", "Estructura THERE + BE + A + ADJECTIVE + NOUN", "Preposiciones de tendencias: from…to, by, of, at, between…and", "Pasiva para el juego de la culpa: it was written by…", "Past Simple para reportar resultados — pero comprueba siempre el tiempo verbal"]',
 '[{"term":"To fall / fell","definition":"Caer — Sales fell slightly"},
   {"term":"To drop / dropped","definition":"Bajar de golpe — Prices dropped sharply"},
   {"term":"To decrease","definition":"Disminuir — The percentage decreased significantly"},
   {"term":"To increase","definition":"Aumentar — The number of x increased dramatically"},
   {"term":"Slightly","definition":"Ligeramente, poco a poco"},
   {"term":"Sharply","definition":"Bruscamente, de forma pronunciada"},
   {"term":"Significantly","definition":"De forma significativa"},
   {"term":"Dramatically","definition":"Drásticamente"},
   {"term":"A slight / gradual / dramatic / steady rise","definition":"Una subida ligera / gradual / drástica / constante"},
   {"term":"A fall / drop / decline","definition":"Una caída / bajada / descenso"},
   {"term":"Peak","definition":"Punto máximo — It peaked at 10 units"},
   {"term":"Lowest point","definition":"Punto mínimo"},
   {"term":"To remain stable","definition":"Mantenerse estable"},
   {"term":"Total payments volume","definition":"Volumen total de pagos"},
   {"term":"To fall short of expectations","definition":"Quedarse por debajo de las expectativas"},
   {"term":"To notch (accounts)","definition":"Alcanzar una cifra"},
   {"term":"To lure (customers)","definition":"Atraer clientes"},
   {"term":"To take the blame","definition":"Asumir la culpa"},
   {"term":"To get to the bottom of it","definition":"Llegar al fondo del asunto"}]',
 '["SUBJECT + VERB + ADVERB → Sales fell slightly. / Prices dropped sharply. / The percentage decreased significantly. / The number of users increased dramatically.",
   "THERE + BE + A + ADJ + NOUN → There is a slight rise in sales. / There was a gradual fall in the price of x. / There has been a dramatic drop in the rate. / There will be a steady decline in the number.",
   "It decreased from 10 to 4. / There was a drop of 6 units. / It dropped by 6 units.",
   "A decrease in the number of… / Between 2004 and 2008… / From 2004 to 2008…",
   "It started at 4 units. / It peaked at 10 units. / It dropped by 8 units to its lowest point at 2 units.",
   "It increased to 6 units. / It remained stable between 2008 and 2010. / It finished at 6 units in 2010.",
   "According to this chart, …",
   "If you look at… you''ll see…",
   "It is said that …"]',
 '[{"title":"Interpret What You See","instructions":"Interpreta la gráfica ''Monthly Sales Data'' (Actual Sales en barras, Expected Sales en línea, Profit en área) usando las frases de arranque.","items":["According to this chart, there was a peak in sales in April.","If you look at January, you can see that we made $20K (20,000 dollars).","It is said that we had a huge drop in profits between April and May.","Ahora tú: describe el pico de abril con ''High Renewals''","Ahora tú: compara Actual Sales vs Expected Sales en septiembre","Ahora tú: describe qué pasó con el Profit entre octubre y noviembre"]},
   {"title":"Construye frases de tendencia","instructions":"Combina las columnas para crear 5 frases distintas. Recuerda: el verbo suele ir en pasado, pero compruébalo siempre.","items":["Sujetos: Sales · Prices · The percentage · The number of x","Verbos: fell · dropped · decreased · increased","Adverbios: slightly · sharply · significantly · dramatically","Variante: There is/was/has been/will be a + slight/gradual/dramatic/steady + rise/fall/drop/decline + in sales/in the price of x/in the rate/in the number"]},
   {"title":"GAME: The Blame Game (Passive Voice Edition)","instructions":"El project manager detecta un problema en la tarea actual y convoca una reunión para llegar al fondo y saber quién lo causó. Nadie quiere asumir la culpa. Responde siempre en voz pasiva.","items":["Project Manager: Taylor, how was the code implemented incorrectly?","Team Member 1: Umm, I don''t know. It was written by Kevin.","Team Member 2 (Kevin): Excuse me. The implementation was done by Juan.","Team Member 3: No. I was nowhere near the code. The last check was made by Jane.","Project Manager: Thanks for the input. After a final pass, it was implemented incorrectly by me. Back to work, please."]}]',
 '{"title":"Presentation Time: FinTech Growth Report","scenario":"Elige una empresa FinTech conocida y presenta su informe de crecimiento interpretando sus cifras y tendencias.","remember":["1. Elige una empresa FinTech","2. Usa el vocabulario de esta lección (verbos de cambio, adverbios y preposiciones de tendencia)","3. Límite de tiempo: 5 minutos","Apóyate en ''According to this chart…'' e ''If you look at… you''ll see…''"],"example":"In the final three months of the year, PayPal''s revenue climbed 13% to $6.9 billion, the smallest increase in two years. Total payments volume climbed just 23% to $339.5 billion in the final three months of last year, as their former parent company, EBay Inc., continues to move payment offerings away from PayPal. That was the smallest increase in two years and fell short of analysts'' expectations. PayPal had said it believes it will notch 750 million active accounts on its platform by 2025. To achieve that goal, the company has been spending more on marketing campaigns to lure new customers to PayPal''s offerings."}',
 ''),

('c1000000-0000-0000-0000-000000000010', 10, 'f2000000-0000-0000-0000-000000000002',
 'Project Presentation',
 'MÓDULO 2 · Integración: preparar la presentación de un proyecto en el que trabajas actualmente y hablar de experiencias previas.',
 '["División del discurso en partes: First / The second point / And finally / To sum up", "Past Simple para narrar el proyecto", "Frases de opinión y de acuerdo/desacuerdo"]',
 '[{"term":"To look something over","definition":"Revisar algo por encima"},
   {"term":"Memo","definition":"Comunicación interna breve"},
   {"term":"To refresh (a page)","definition":"Actualizar una página"},
   {"term":"FinTech","definition":"Tecnología aplicada a servicios financieros"},
   {"term":"To sum up","definition":"En resumen — cierre de presentación"}]',
 '["Today I''d like to discuss a project that we worked on last week.",
   "I divided my talk into three parts.",
   "First, I honestly believed that…",
   "The second point I''d like to consider is…",
   "And finally, I''d like to talk about…",
   "To sum up, …",
   "In my opinion, …",
   "I agree with… / I disagree with… / I understand but…",
   "To be honest… / Actually, … / No comment. What do you think?"]',
 '[{"title":"Discussion Alley: Wake Up The Audience","instructions":"Debate estas preguntas sobre aperturas de presentación.","items":["1. ¿Qué aperturas captan seguro la atención del público?","2. Si tu producto fuera un ''Waterproof Laptop'', ¿qué frases de apertura usarías?","3. ¿Qué tipo de producto es el más difícil de presentar?","4. ¿Alguna presentación de producto te ha impresionado? ¿Cuál?"]},
   {"title":"To Agree or To Disagree","instructions":"Posiciónate ante estas afirmaciones usando las frases de acuerdo/desacuerdo.","items":["''FinTech is only for younger generations to understand and use.'' — A. Parker","''Who needs cash when you can have bitcoins.'' — B. Smith"]}]',
 '{"title":"Presenta tu proyecto actual","scenario":"Prepara la presentación de un proyecto en el que trabajas ahora. Habla también de experiencias previas.","remember":["Escribe las ideas principales","Divide tu charla en partes","El público debe hacer preguntas de seguimiento"]}',
 '')

ON CONFLICT (class_number) DO NOTHING;
